<%@ Page Language="C#" AutoEventWireup="true"  CodeFile="Default.aspx.cs" Inherits="_Default" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <link href="estilos.css" type="text/css" rel="Stylesheet" />
    <title>Página sin título</title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <div class="titulo">Alumnos</div>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" BorderStyle="Solid"
            DataSourceID="alumnoData" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnSelectedIndexChanged="GridView1_SelectedIndexChanged">
            <Columns>
                <asp:BoundField DataField="Codigo" HeaderText="Codigo" SortExpression="Codigo" />
                <asp:BoundField DataField="Nombre" HeaderText="Nombre" SortExpression="Nombre" />
                <asp:BoundField DataField="Apellido" HeaderText="Apellido" SortExpression="Apellido" />
            </Columns>
        </asp:GridView>
        <asp:ObjectDataSource ID="alumnoData" runat="server" SelectMethod="consultar" TypeName="clAlumno.AlumnoData" DataObjectTypeName="clAlumno.Alumno" DeleteMethod="borrar" InsertMethod="insertar" UpdateMethod="actualizar" OnSelecting="alumnoData_Selecting" >
        </asp:ObjectDataSource>
        <asp:Label ID="Label1" runat="server" Text="Label" Width="307px"></asp:Label></div>
    </form>
</body>
</html>
